package files.reports;

public enum ReportParameterEnum {
    PRICE_COMPARISON_REPORT_PATH,
    PRICE_COMPARISON_RESULT,
    PRICE_COMPARISON_SHEET_NAMES,

    REPORT_PATH,
    REPORT_ITEMS,
    REPORT_COLUMNS
}
